### ISSUE TITLE
Grab quotes from wikiquote category authors

### ISSUE THREAD

**Issue by joeval** [myano/jenni#112]
randomly grab a quote (*user-optionally 'bold' (mainquote) or any* - have a setting) from a user-chosen category, like https://en.wikiquote.org/wiki/Category:Philosophers

would love it -- great bot, thanks!

**Comment by kaneda** [comment]
@myano you can assign this one to me, I'll do it by choice of 	Category:Television_shows, Category:Proverbs, Category:Literary_works, Category:Films, Category:Philosophers or random from all of those.

**Comment by kaneda** [comment]
@joeval https://github.com/myano/jenni/pull/141
