### ISSUE TITLE
"IndexError: no such group"

### ISSUE THREAD

**Issue by KanchiMoe** [myano/jenni#115]
> [04:20:38 A] <Chiyo> .tell Iciloo,ecks http://quotes.wikimissingfoundation.org/?281
> [04:20:39 A] <+jenni> IndexError: no such group (file "/home/jenni/jenni/modules/tell.py", line 62, in f_remind)

**Comment by ElGatoSaez** [comment]
I'm having that error, but not with that module, I created one but doesn't knows what is input.group 3

**Comment by myano** [comment]
@ElGatoSaez do you remember which module it was? also the input.group numbers are based on which set of paranthesis are caught. If your function only has a .commands then any text after the ".mytrigger" in the IRC line is "input.group(2)", if you use a rule with regexp, the group numbers match from left to right based on your capturing regexps rules.

**Comment by ElGatoSaez** [comment]
@myano I was just coding, I'm newbie, so I didn't knew that. Thanks for making my mind and create tools that helped me to learn code.
