### ISSUE TITLE
Begin migration to urllib3

### ISSUE THREAD

**Issue by kaneda** [myano/jenni#135]
Slowly migrate to urllib3 (or the requests framework if you're lazy). This doesn't need to be done all at once, but as we make changes to modules that around connections (or write new modules, or overhaul old modules) we should move to urllib3

**Comment by myano** [comment]
The only reason I'm against using requests is because it seems older versions of Python don't always have it available and not everybody can install it via pip easily.

Otherwise, I love requests.

**Comment by kaneda** [comment]
@myano after some investigation I'm not sure it's worth going to urllib3. My concern was regarding long-term support, but I believe urllib and urllib2 will continue support through Python 3

**Comment by myano** [comment]
@kaneda Yea, I say we close this. For now, if anyone writing a module wants to grab stuff from the Internet, they can either do web.get or proxy.get. Personally, I recommend doing the proxy.get
