### ISSUE TITLE
Disconnects repeatedly

### ISSUE THREAD

**Issue by afuhrtrumpet** [myano/jenni#153]
I cannot deploy the newest version of jenni. The bot simply connects to freenode, and disconnects without ever joining a channel. This was not a problem with an older version.

**Comment by kaneda** [comment]
@afuhrtrumpet can you gist the full log up to disconnect?

**Comment by afuhrtrumpet** [comment]
Is that in a text file, or just the command line output?

**Comment by kaneda** [comment]
@afuhrtrumpet the command line output and/or the jenni.log please

**Comment by kaneda** [comment]
@afuhrtrumpet i just tried with SASL enabled and disabled and was unable to reproduce off of master.

**Comment by afuhrtrumpet** [comment]
I have SASL disabled, does that matter?

**Comment by kaneda** [comment]
@afuhrtrumpet i tried it both ways, i can't reproduce. can you post a log?

**Comment by afuhrtrumpet** [comment]
@kaneda Here you go: https://gist.github.com/afuhrtrumpet/af1eea0d62fdb92b99a1

**Comment by kaneda** [comment]
@afuhrtrumpet is line 48 of your modules/sasl.py:
```python
    if hasattr(jenni.config, 'nick') and jenni.config.nick is not None and hasattr(jenni.config, 'password') and jenni.config.password is not None:
```

**Comment by afuhrtrumpet** [comment]
@kaneda Yes.

**Comment by kaneda** [comment]
@afuhrtrumpet Can you do a search for "Session" in bot.py. There should be no instance of it, but your log indicates there is.

**Comment by kaneda** [comment]
@afuhrtrumpet i see a different error in my log related to yelpapi. Is there a dependency that we should be aware of?

**Comment by kaneda** [comment]
@afuhrtrumpet updated docs in https://github.com/myano/jenni/pull/146 to reflect yelpapi dependency

**Comment by kaneda** [comment]
@afuhrtrumpet i continue to not be able to reproduce your issue. Can you checkout master and do "git reset --hard HEAD" please and then try again?

**Comment by afuhrtrumpet** [comment]
Hmm, it seems like this was fixed within the last few commits.
