### ISSUE TITLE
startup.py relies on RPL_LUSERCLIENT event

### ISSUE THREAD

**Issue by Bekey** [myano/jenni#157]
Inside the module startup.py, the function responsible for joining channels supplied in the config file relies on the IRC event 251 RPL_LUSERCLIENT to fire off the function.

However some IRC servers, most notably irc.twitch.tv, do not send this event.

https://github.com/myano/jenni/blob/master/modules/startup.py#L73

Also for what it's worth, if the function is fired off the lines
```python
if hasattr(jenni.config, 'serverpass'):
    jenni.write(('PASS', jenni.config.serverpass))
```
cause a disconnect since jenni has already authenticated herself in irc.py
https://github.com/myano/jenni/blob/master/irc.py#L224-L225
```python
if not self.use_sasl and self.password:
    self.write(('PASS', self.password))
```

**Comment by kaneda** [comment]
@Bekey can you try https://github.com/myano/jenni/pull/167 and let me know if it fixes the problem?

**Comment by kaneda** [comment]
Considering closed, @Bekey let me know if this is not the case
