### ISSUE TITLE
url.py broke?

### ISSUE THREAD

**Issue by nnoided** [myano/jenni#199]
url.py has stopped working for me, fairly sure the module is broken. 

 .title google.com
01:16 <+jenni> (<html><head><meta http-equiv="content-type" content="text/html;charset=utf-8"><title>503 Over Quota</title><style></

**Comment by myano** [comment]
The Google App Engine went over the quota yesterday.

If you see the "503 Over Quota" thingy it'll fix itself after 24 hours when the quota resets.
