### ISSUE TITLE
Can't start/reload new module during jenni-session

### ISSUE THREAD

**Issue by nickurt** [myano/jenni#204]
I created a new module when jenni was running and I runned

    .reload_conf 
    // user: Reloaded configs

But after that, the new module was not running, even tried with

    bot: reload moduleName
    // user: moduleName: no such module!

was not working ...

**Comment by kaneda** [comment]
@nickurt Sounds like you didn't register the module / put it in the right place.

**Comment by nickurt** [comment]
I saved the module in the jenni/modules folder ...

**Comment by Bekey** [comment]
You'd probably have to add jenni.setup() after reloading the configs, to make newly created modules register with the bind commands.

**Comment by nickurt** [comment]
@Bekey Thanks, after I did

    upd: reload * 

It works, thanks for your help
