### ISSUE TITLE
py.py not working

### ISSUE THREAD

**Issue by lenisko** [myano/jenni#207]
There is a problem with https://tumbolia.appspot.com/py/ , hope not permanent.
Any workaround other than exec("python " + user_script) ?; )

**Comment by myano** [comment]
Yes, replace the "tumoblia" with "tumbolia-two" and you are good to go.
On Aug 30, 2015 08:02, "Jacob" <notifications@github.com> wrote:
>
> There is a problem with https://tumbolia.appspot.com/py/ , hope not
permanent.

**Comment by lenisko** [comment]
thanks!
