### ISSUE TITLE
Weather: Gisgraphy is now Protected

### ISSUE THREAD

**Issue by Jarada** [myano/jenni#208]
Hey all,

So with the weather command, the [Gisgraphy Geocoding](http://www.gisgraphy.com/forum/viewtopic.php?f=4&t=26013&sid=94c800dddf0d7d5ca9121b90cf51754f) is now disabled for API access for bots. From my initial look at their website, I believe the free geocoding API services are just for testing before you use the premium ones.

This means that now .weather command no longer functions. For the moment as a workaround, you can revert parts of commit 15f39262 where this was introduced, but it would be nice to use this thread to discuss possible alternatives to Gisgraphy as a JSON API would be nice.

**Comment by myano** [comment]
I fixed this a little while ago but apparently missed this issue posted here. As long as you have at least commit 768613399de5417b06bd44353eac9de98a984c10 the GPS coords stuff has been fixed.
