### ISSUE TITLE
How to reload a module?

### ISSUE THREAD

**Issue by joelwmale** [myano/jenni#214]
I've read the wiki, and tried a billion messages. But can't get the reload working.

The module is loading, but not quite sure on the syntax.

It says to message jenni directly.

So i've tried:

Jenni: reload commands.py
jenni: reload commands.py
(Priv msg):
reload commands.py
.reload commands.py

But none of its working, no reply from jenni, nothing.

Any help?

**Comment by KindOne-** [comment]
This can be done in channel and in query, assuming your ```owner``` and/or ```admin``` settings in the ```~/jenni/default.py``` match you as they are case sensitive.
```
<foobar> jenni: reload admin
<jenni> foobar: <module 'admin' from '/home/jenni/jenni/modules/admin.pyc'> (version: 2015-07-08 04:29:37)
```

**Comment by joelwmale** [comment]
Ah... Sorry. I wasn't owner and/or admin in the settings on the account I was trying. Thank you!
