### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by joelwmale** [myano/jenni#217]
Hi all,

Getting this error when I try and reload a custom module (named commands).

Full error:

ValueError: list.remove(x): x not in list (file "/usr/local/lib/python2.7/dist-packages/jenni/bot.py", line 176, in unregister)

The module is in /home/user/.jenni/modules/, and its running (all my commands in there work) but I just can't reload the module.

I CAN reload any other module:

JoelM: <module 'admin' from '/home/joel/.sopel/modules/admin.py'> (version: 2015-10-22 13:25:09)

Any ideas?

**Comment by myano** [comment]
Can you please provide a copy of your module, or at least the function in your module that you are triggering? *and* a copy of the full traceback you seen in stdout while running jenni when this happens, please?

**Comment by joelwmale** [comment]
It seems to only happen sometimes. Might be caused by an error in my python code, not quite sure. Next time I get the error, i'll do the above.
