### ISSUE TITLE
Remove the need for . before each message?

### ISSUE THREAD

**Issue by joelwmale** [myano/jenni#219]
Not an issue, but is there a way to remove the need for a . before each message?

So I could just say "weather" for example. Been looking through all the base code but can't find where it listens.

**Comment by lenisko** [comment]
It was somewhere in __irc.py__ but... don't do that.. it's bad for you/other guys/bot.

**Comment by joelwmale** [comment]
Hmm I can't seem to find it in irc.py. It's only be and the bot, so it shouldn't be bad.

**Comment by myano** [comment]
You could try setting the variable "prefix" in your default.py to just an empty string:

    prefix = ''

That might work but very well will have unintended consequences, because that variable is used to build a regular expression to match commands/rules.

**Comment by joelwmale** [comment]
I understand. Thank you @myano.
