### ISSUE TITLE
Disallow game starting on wild card

### ISSUE THREAD

**Issue by MJ94** [myano/jenni#220]
If a game starts on a wild card (WD4), no players can reasonably play and have to keep drawing numerous times unless they .leave and restart. The top card should only start as a colored number card.

According to the official uno rules:
>"Return card to deck, shuffle, flip top card to start discard pile"

**Comment by easymac** [comment]
Also, after this scenario was encountered, starting a new game resulted in the following error:

`IndexError: string index out of range (file "/home/jenni/jenni/modules/unobot.py", line 407, in cardPlayed)`

**Comment by MAGICCC** [comment]
hm, found my mistake. Either wait for the PR or change your files manually
https://github.com/myano/jenni/pull/221

**Comment by myano** [comment]
I merged this change in 16 days ago.
