### ISSUE TITLE
Calc broken

### ISSUE THREAD

**Issue by lenisko** [myano/jenni#226]
user> .wa 3+3
jenni> Couldn't grab results from json stringified precioussss.

Problem with https://tumbolia-two.appspot.com/wa/

**Comment by myano** [comment]
So after a little bit of research, I'm sad to say that we're having to deprecate that WolframAlpha's global capability for everybody via that URL.

> This feature has been deprecated due to WolframAlpha's strict new updates and policies.

However, we just whipped up something that appears to be working but requires the bot runner to acquire API keys from WolframAlpha. I'm waiting for a few more people to test it and try to find some edge cases before I'll clean up the code and push it live.

I should have it live within the next few days.

**Comment by myano** [comment]
.wa is now working and the changes have been published in commit 8e3478840df5938df939ab7955f5363ee8855a84
