### ISSUE TITLE
Add ability to decide what to make for dinner

### ISSUE THREAD

**Issue by paradigm** [myano/jenni#58]
Presumably utilizing this website: http://whatthefuckshouldimakefordinner.com/

Extra points if it either has an alternative command or, even better, remembers per-user whether vegetarian.

**Comment by kaneda** [comment]
@paradigm I'm calling this guy closed. I don't think per-user is reasonable until, in the least, https://github.com/myano/jenni/issues/107 is done

**Comment by myano** [comment]
Actually, I'm going to re-open this. I have pretty much done most of it in osu_osc.py

**Comment by kaneda** [comment]
@myano sorry about that, cool

**Comment by myano** [comment]
No worries, you didn't know.

If you PM jenni you can play around with ".dinner" It currently doesn't take any extra input.

There is also a ".food" but that is extremely specific to Columbus, Ohio.

**Comment by myano** [comment]
The functionality is now being provided via:

- [food.py](https://github.com/myano/jenni/blob/master/modules/food.py)
- [dinner.py](https://github.com/myano/jenni/blob/master/modules/dinner.py)
