### ISSUE TITLE
.help doesn't work correctly

### ISSUE THREAD

**Issue by 303i** [myano/jenni#83]
It lists items that aren't actually commands, doesn't list all commands, isn't formatted, and doesn't seem to actually work when you ask for help on an item.

I would attempt to fix it myself, but I have no idea where it is in the source.

Also, a description update on the channeladmin module would be nice, its still states it uses m5 verification and should say that users need to be added to the auth_list for it to work.
.

**Comment by kaneda** [comment]
I'll try to resolve this, at least in part, as part of https://github.com/myano/jenni/issues/142

**Comment by kaneda** [comment]
@303i check out https://github.com/myano/jenni/wiki for a better list that I've compiled.
